import { Product } from "@/types/product";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Red Roses Bouquet",
    price: 1299,
    slug: "red-roses-bouquet",
    image: "/images/red-roses.jpg",
    category: "exotic",
  },
  {
    id: "2",
    name: "Orchid Exotic Mix",
    price: 2499,
    slug: "orchid-exotic-mix",
    image: "/images/orchid-mix.jpg",
    category: "exotic",
  },
  {
    id: "3",
    name: "Lotus Flower Pooja Set",
    price: 899,
    slug: "lotus-pooja-set",
    image: "/images/lotus-pooja.jpg",
    category: "pooja",
  },
  {
    id: "4",
    name: "Marigold Garland - Traditional",
    price: 599,
    slug: "marigold-garland-traditional",
    image: "/images/marigold-garland.jpg",
    category: "pooja-garlands",
  },
  {
    id: "5",
    name: "Festive Toran - Golden",
    price: 1599,
    slug: "festive-toran-golden",
    image: "/images/toran-golden.jpg",
    category: "festive-torans",
  },
  {
    id: "6",
    name: "Wedding Bridal Bouquet",
    price: 4999,
    slug: "wedding-bridal-bouquet",
    image: "/images/wedding-bouquet.jpg",
    category: "wedding",
  },
  {
    id: "7",
    name: "Customized Flower Arrangement",
    price: 3499,
    slug: "custom-arrangement",
    image: "/images/custom-arrangement.jpg",
    category: "customized",
  },
  {
    id: "8",
    name: "Sunflower Bunch - Fresh",
    price: 799,
    slug: "sunflower-bunch",
    image: "/images/sunflower-bunch.jpg",
    category: "exotic",
  },
];